language: node_js
node_js:
  - "8"

branches:
  only:
  - master
  - draft

script:
  - echo "Current branch is ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
  - if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "master" ]; then
    ./scripts/sync.sh;
    fi
  - if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "draft" ]; then
    ./scripts/preview-build.sh && ./scripts/preview-push.sh;
    fi
